version: 2.1

jobs:
  ip_ranges_macos:
    circleci_ip_ranges: true
    macos:
      xcode: 11.7.0
    steps:
        - checkout
        - run: | 
            export SERVER_IP=`ipconfig getifaddr en0`
            echo $SERVER_IP
workflows:
  test_macos_ip_ranges:
    jobs:
      - ip_ranges_macos 
