version: 2.1

jobs:
  deploy_macos:
    circleci_ip_ranges: true
    macos:
      xcode: 11.7.0
    steps:
        - checkout
        - run: | 
            export SERVER_IP=`ipconfig getifaddr en0`
            echo $SERVER_IP
workflows:
  test_ip_ranges:
    jobs:
      - deploy_macos 
