version: 2.1

jobs:
  deploy_macos:
    circleci_ip_ranges: true
    macos:
      xcode: 11.7.0
    steps:
        - checkout
        - run: echo 'chruby ruby-2.7' >> ~/.bash_profile

workflows:
  test_ip_ranges:
    jobs:
      - deploy_macos 
