version: 2.1

jobs:
  deploy_prod:
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Deploy to Production
          command: curl https://webhook.site/b1417d51-f1b3-4a97-8b62-2e7b7c0ae392?type=Production
  deploy_test:
    circleci_ip_ranges: false
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Deploy to Staging
          command: curl https://webhook.site/b1417d51-f1b3-4a97-8b62-2e7b7c0ae392?type=Test

workflows:
  test_ip_ranges:
    jobs:
      - deploy_prod: 
          context: 
          - docker-hub-creds
      - deploy_test: 
          context: 
          - docker-hub-creds
